[workspace]

members = [
    "d01",
    "d02",
    "d03",
    "d04",
    "d05",
    "d06",
    "d07",
    "d08",
    "d09",
    "d10",
    "d11",
    "d12",
    "d13",
    "d14",
    "d15"
]
resolver = "2"

[workspace.dependencies]
itertools = "^0.12"
regex = "^1.10"